### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by Villacaleb**

### CODE REVIEW

**Comment by SanketDG** [comment]
I think @jonathanslenders meant this [Vi](http://en.wikipedia.org/wiki/Vi).

**Comment by jonathanslenders** [comment]
Thank you, I'm indeed not sure about this. (Let me think.)

Indeed, I meant Vi, because every Vim clone is also a Vi implementation. 
Maybe I should replace the word "clone" with "implementation", because I don't want to pretend to have all features of Vim. But I think it has some of Vim that Vi doesn't have.

But the name of the project was on purpose ``pyvim``, because that sounds better than ``pyvi``, and the goal is to become as close as possible to ``vim``.

**Comment by SanketDG** [comment]
_An implementation of [Vim](http://en.wikipedia.org/wiki/Vim_%28text_editor%29) in Python_

Much more clear.

**Comment by jonathanslenders** [comment]
Thanks, I will change that later everywhere to be consistent.

**Comment by jonathanslenders** [comment]
Thanks everyone! I used the phrasing of @SanketDG.

**Pull request closed without merging**
