### PR TITLE
Implement file explorer

### PR DESCRIPTION
**Pull request by davidbrochart**
When opening a directory, the file or directory under the cursor can be opened by pressing Enter.
I used a `file_explorer` attribute for each `editor_buffer`, and for the `editor`, which is synced with the current buffer. When the `file_explorer` attribute is not empty, it means that we are in "file explorer mode" and its content is the path of the directory we are in.

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Thank you @davidbrochart,
This looks very nice! I'll merge it later when I have some time to review it.

Also, pyvim didn't got a lot of attention lately. Which is because I've been focussing mostly on prompt_toolkit 2.0. When that's released I'd like to make sure that pyvim runs on 2.0 as well, which should solve a couple of pyvim issues.

**Comment by davidbrochart** [comment]
Hi @jonathanslenders, this feature is quite handy. Any chance you can merge it?

**Comment by jonathanslenders** [comment]
Hi @davidbrochart, this took me way too long, but finally I've merged it here: https://github.com/jonathanslenders/pyvim/commit/a511949ff13bffcef64e5421e7a939e997efb1b9
I had to do a couple of modifications due to some changes to prompt_toolkit 2.0 that we had in the meantime.

**Comment by davidbrochart** [comment]
Thanks!

**Pull request closed without merging**
